export const issues = [
  {
    id: 1,
    title: "Fix login page bug on mobile view",
    owner: "John Doe",
    status: "In Progress",
    creationDate: "2024-09-02",
    effortRequired: 3,
    estimatedCompletionDate: "2024-09-05",
  },
  {
    id: 2,
    title: "Update the API documentation",
    owner: "Jane Smith",
    status: "To Do",
    creationDate: "2024-09-01",
    effortRequired: 2,
    estimatedCompletionDate: "2024-09-03",
  },
  {
    id: 3,
    title: "Optimize database queries",
    owner: "Emily Johnson",
    status: "In Review",
    creationDate: "2024-09-01",
    effortRequired: 5,
    estimatedCompletionDate: "2024-09-06",
  },
  {
    id: 4,
    title: "Design the new dashboard UI",
    owner: "Michael Brown",
    status: "To Do",
    creationDate: "2024-09-02",
    effortRequired: 7,
    estimatedCompletionDate: "2024-09-09",
  },
  {
    id: 5,
    title: "Implement caching for API requests",
    owner: "Chris Green",
    status: "In Progress",
    creationDate: "2024-09-02",
    effortRequired: 4,
    estimatedCompletionDate: "2024-09-06",
  },
  {
    id: 6,
    title: "Set up CI/CD pipeline",
    owner: "Anna White",
    status: "Completed",
    creationDate: "2024-08-30",
    effortRequired: 2,
    estimatedCompletionDate: "2024-09-01",
  },
  {
    id: 7,
    title: "Refactor authentication module",
    owner: "David Black",
    status: "To Do",
    creationDate: "2024-09-02",
    effortRequired: 6,
    estimatedCompletionDate: "2024-09-08",
  },
  {
    id: 8,
    title: "Fix CSS issues on the homepage",
    owner: "Sophia Blue",
    status: "In Progress",
    creationDate: "2024-09-02",
    effortRequired: 3,
    estimatedCompletionDate: "2024-09-04",
  },
  {
    id: 9,
    title: "Create unit tests for user module",
    owner: "James Violet",
    status: "To Do",
    creationDate: "2024-09-02",
    effortRequired: 4,
    estimatedCompletionDate: "2024-09-06",
  },
  {
    id: 10,
    title: "Improve performance on mobile devices",
    owner: "Olivia Red",
    status: "In Review",
    creationDate: "2024-09-01",
    effortRequired: 5,
    estimatedCompletionDate: "2024-09-05",
  },
  {
    id: 11,
    title: "Update privacy policy page",
    owner: "Liam Gray",
    status: "Completed",
    creationDate: "2024-08-29",
    effortRequired: 1,
    estimatedCompletionDate: "2024-08-30",
  },
  {
    id: 12,
    title: "Implement dark mode feature",
    owner: "Ella Silver",
    status: "To Do",
    creationDate: "2024-09-02",
    effortRequired: 4,
    estimatedCompletionDate: "2024-09-06",
  },
  {
    id: 13,
    title: "Fix search functionality bug",
    owner: "William Gold",
    status: "In Progress",
    creationDate: "2024-09-02",
    effortRequired: 2,
    estimatedCompletionDate: "2024-09-04",
  },
  {
    id: 15,
    title: "Redesign the footer section",
    owner: "Mia Bronze",
    status: "To Do",
    creationDate: "2024-09-02",
    effortRequired: 3,
    estimatedCompletionDate: "2024-09-05",
  },
  {
    id: 16,
    title: "Add new features to the analytics page",
    owner: "Lucas Copper",
    status: "In Progress",
    creationDate: "2024-09-02",
    effortRequired: 6,
    estimatedCompletionDate: "2024-09-08",
  },
];
